"""Deterministic design checks for candidate-facing Career OS resume files.

This module is intentionally conservative. It validates objective, repeatable
properties of the generated artifacts; it never treats a missing visual review
as a pass and it never changes resume content. A failed result is a browser
execution blocker until a corrected current JD-specific artifact is generated.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

from docx import Document
from pypdf import PdfReader


_REQUIRED_HEADINGS = (
    "PROFESSIONAL SUMMARY",
    "SKILLS",
    "EXPERIENCE",
    "EDUCATION",
)
_FORBIDDEN_LABELS = (
    "(tailored)",
    "tailored resume",
    "generated by career os",
    "internal-generation",
)


def _pdf_text(path: Path) -> str:
    reader = PdfReader(str(path))
    return "\n".join((page.extract_text() or "") for page in reader.pages)


def audit_resume_design(resume_files: Mapping[str, object]) -> dict[str, Any]:
    """Return deterministic design-QA evidence for the current resume artifacts.

    The required one-page single-column presentation is enforced through the
    generated PDF page count and the DOCX table count. Text extraction also
    catches visible internal labels, broken replacement glyphs, and missing
    conventional ATS section headings. It does not make subjective aesthetic
    claims; a human visual review can be recorded separately when required.
    """
    issues: list[str] = []
    warnings: list[str] = []
    metrics: dict[str, Any] = {}

    pdf_value = resume_files.get("pdf")
    docx_value = resume_files.get("docx")
    pdf_path = Path(str(pdf_value)) if pdf_value else None
    docx_path = Path(str(docx_value)) if docx_value else None

    if not pdf_path or not pdf_path.is_file():
        issues.append("final PDF is missing")
    else:
        try:
            reader = PdfReader(str(pdf_path))
            metrics["pdf_pages"] = len(reader.pages)
            if len(reader.pages) != 1:
                issues.append(f"PDF must be exactly one A4 page; found {len(reader.pages)} pages")
            text = _pdf_text(pdf_path)
            lowered = text.casefold()
            if "\ufffd" in text or "\x00" in text:
                issues.append("PDF contains broken or replacement characters")
            for label in _FORBIDDEN_LABELS:
                if label in lowered:
                    issues.append(f"PDF contains internal-generation label: {label}")
            for heading in _REQUIRED_HEADINGS:
                if heading.casefold() not in lowered:
                    issues.append(f"PDF is missing required heading: {heading}")
        except Exception as exc:  # PDF parser failures must never pass silently.
            issues.append(f"PDF design inspection failed: {exc}")

    if not docx_path or not docx_path.is_file():
        issues.append("final DOCX is missing")
    else:
        try:
            document = Document(str(docx_path))
            metrics["docx_tables"] = len(document.tables)
            if document.tables:
                issues.append("DOCX must use a single-column ATS-readable layout without tables")
            paragraph_text = "\n".join(paragraph.text for paragraph in document.paragraphs)
            if "\ufffd" in paragraph_text or "\x00" in paragraph_text:
                issues.append("DOCX contains broken or replacement characters")
        except Exception as exc:
            issues.append(f"DOCX design inspection failed: {exc}")

    if not issues and not metrics:
        warnings.append("No design-QA metrics were available")

    return {
        "passed": not issues,
        "issues": issues,
        "warnings": warnings,
        "metrics": metrics,
        "method": "deterministic_pdf_docx_design_contract_v1",
    }
