"""Offline snapshot of the Career Evidence Vault for deterministic tests.

Source of truth remains the live Notion Career Evidence Vault.
This snapshot mirrors the 26 items migrated in Phase 1 and must not
promote any Needs-Confirmation or Self-Directed items.
"""

from .evidence import EvidenceItem

VAULT_SNAPSHOT: list[EvidenceItem] = [
    EvidenceItem(
        claim="AWS / cloud application support at FactSet",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Support enterprise/workforce application in a cloud environment; troubleshoot application issues and coordinate technical escalation.",
        evidence_source="User direct confirmation; Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Supported cloud-hosted applications and performed application troubleshooting in an AWS/cloud environment at FactSet.",
        unsafe_wording="Owned AWS architecture / designed EC2/S3/IAM production infrastructure",
        notes="Specific AWS services remain Self-Directed labs unless separately confirmed.",
    ),
    EvidenceItem(
        claim="ServiceNow / ITSM ticket and incident management",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="L1/L2 support, ticket triage, incident handling, escalation, SLA awareness.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Managed support tickets and incident workflow in ServiceNow, including triage, escalation, and resolution hand-off.",
    ),
    EvidenceItem(
        claim="Oracle / PL/SQL for application and data investigation",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Investigate application/data issues using database queries and PL/SQL-based analysis.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Used Oracle SQL and PL/SQL to investigate application and data issues during support work.",
    ),
    EvidenceItem(
        claim="Unix/Linux environments for troubleshooting",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Use Unix/Linux environments and commands while troubleshooting application/operational issues.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Worked in Unix/Linux environments to troubleshoot application and operational issues.",
    ),
    EvidenceItem(
        claim="Control-M batch/scheduled job monitoring and troubleshooting",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Occasional",
        context="Monitor/investigate scheduled jobs and batch processing workflows as part of application/operational support.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Monitored and investigated Control-M scheduled jobs as part of application support.",
    ),
    EvidenceItem(
        claim="REST APIs / JSON / Postman for integration troubleshooting",
        category="Tool",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Investigate API requests/responses and integration issues during application troubleshooting.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Used REST APIs, JSON, and Postman to investigate integration and API-related application issues.",
    ),
    EvidenceItem(
        claim="UAT / release validation participation",
        category="Process",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Occasional",
        context="Validate fixes/releases, reproduce defects, document outcomes and coordinate with technical teams.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Participated in UAT and release validation, including defect reproduction and outcome documentation.",
    ),
    EvidenceItem(
        claim="SOP / runbook documentation",
        category="Process",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Document recurring troubleshooting procedures and operational support workflows.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Created and maintained SOPs and runbooks for troubleshooting and operational support workflows.",
    ),
    EvidenceItem(
        claim="L1/L2 product support and ticket triage",
        category="Responsibility",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="Product/customer support and ticket triage for a workforce/time-and-attendance application; escalation to developer teams; SLA awareness; troubleshooting and RCA.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Provided L1/L2 product support including ticket triage, troubleshooting, RCA, and escalation for a workforce application.",
    ),
    EvidenceItem(
        claim="Corporate governance / shareholder activism / SEC filing research and data operations",
        category="Domain",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Research/data operations involving corporate governance and shareholder activism, SEC filings including 10-K, 10-Q and proxy statements.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Performed research and data operations on corporate governance, shareholder activism, and SEC filings (10-K, 10-Q, proxy statements).",
    ),
    EvidenceItem(
        claim="Incident management, ticket management, RCA, SLA support",
        category="Process",
        employer="FactSet Systems India Pvt. Ltd.",
        role="Product Support Engineer / Research Analyst",
        employment_period="Nov 2024 – Jan 2026",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="Core support workflow at FactSet.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Handled incident and ticket management, performed root-cause analysis, and supported SLA commitments.",
    ),
    EvidenceItem(
        claim="Group reservations / event operations (Radisson Blu Edwardian process)",
        category="Responsibility",
        employer="IGT Solutions",
        role="Process Associate / Technical Operations Analyst (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="Backend operations for group reservations and events: client requirements, proposals, contracts, proforma invoices, payment coordination, rate discussions and stakeholder follow-up.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Handled backend group reservations and event-management operations including proposals, contracts, proforma invoices, payment coordination, rate discussion, and stakeholder follow-up.",
    ),
    EvidenceItem(
        claim="Primary technical point of contact for reservation-platform issues",
        category="Responsibility",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="Served as primary technical point of contact for reservation-platform issues affecting global hotel operations.",
        evidence_source="Career Profile",
        confirmation_status="Confirmed-by-User",
        safe_wording="Acted as primary technical point of contact for reservation-platform issues impacting global hotel operations.",
    ),
    EvidenceItem(
        claim="Python for operational reporting and data validation at IGT",
        category="Skill",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; Phase 1 rule requires Needs-Confirmation for IGT technical claims.",
        evidence_source="Career Profile; Phase 1 instruction",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
        notes="Retain in universe; do not promote.",
    ),
    EvidenceItem(
        claim="SQL for operational reporting and data validation at IGT",
        category="Skill",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; Phase 1 rule: Needs-Confirmation.",
        evidence_source="Career Profile; Phase 1 instruction",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
    ),
    EvidenceItem(
        claim="Power Query for operational reporting at IGT",
        category="Tool",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; Phase 1: Needs-Confirmation.",
        evidence_source="Career Profile; Phase 1 instruction",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
    ),
    EvidenceItem(
        claim="Power BI dashboards for reservation accuracy and SLA compliance at IGT",
        category="Tool",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; Phase 1: Needs-Confirmation.",
        evidence_source="Career Profile; Phase 1 instruction",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
    ),
    EvidenceItem(
        claim="REST API testing between reservation and payment systems at IGT",
        category="Tool",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; Phase 1: Needs-Confirmation.",
        evidence_source="Career Profile; Phase 1 instruction",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
    ),
    EvidenceItem(
        claim="UAT for production releases at IGT",
        category="Process",
        employer="IGT Solutions",
        role="Technical Operations Analyst / Associate (Contract)",
        employment_period="Dec 2023 – May 2024",
        professional_status="Unconfirmed",
        usage_level="Unknown",
        context="Listed in Career Profile; treated conservatively as Needs-Confirmation.",
        evidence_source="Career Profile",
        confirmation_status="Needs-Confirmation",
        safe_wording="(Do not use on resume until confirmed)",
    ),
    EvidenceItem(
        claim="Comcast / Xfinity technical troubleshooting (connectivity, modem, Wi-Fi, service)",
        category="Responsibility",
        employer="Concentrix (Comcast process)",
        role="Technical Support Representative",
        employment_period="Nov 2021 – Oct 2022",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="First-line technical troubleshooting for Comcast products; diagnosed connectivity/product issues and performed structured troubleshooting.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Provided first-line technical troubleshooting for Comcast/Xfinity products including connectivity, modem, Wi-Fi, and related service issues.",
    ),
    EvidenceItem(
        claim="Networking fundamentals troubleshooting (TCP/IP, DNS, DHCP, Wi-Fi, VPN)",
        category="Skill",
        employer="Concentrix (Comcast process)",
        role="Technical Support Representative",
        employment_period="Nov 2021 – Oct 2022",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Confirmed networking/connectivity troubleshooting areas for Comcast process.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Troubleshot TCP/IP, DNS, DHCP, Wi-Fi, VPN and related connectivity issues in a customer-support context.",
    ),
    EvidenceItem(
        claim="CRM / ticketing workflow for support cases",
        category="Process",
        employer="Concentrix (Comcast process)",
        role="Technical Support Representative",
        employment_period="Nov 2021 – Oct 2022",
        professional_status="Professional-Confirmed",
        usage_level="Daily/Core",
        context="Log, track and document customer technical-support interactions and resolutions in support systems.",
        evidence_source="Career Profile; Consolidated Role Verification",
        confirmation_status="Confirmed-by-User",
        safe_wording="Created, updated, and closed support cases in CRM/ticketing systems while documenting resolutions.",
    ),
    EvidenceItem(
        claim="AWS specific services (EC2, IAM, S3, CloudWatch, Security Groups/SSH) — personal labs",
        category="Tool",
        employer="Self-Directed / Personal",
        role="Self-directed learning",
        employment_period="N/A",
        professional_status="Self-Directed",
        usage_level="Exposure",
        context="Personal labs/projects. Distinct from professional AWS/cloud application support at FactSet.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Self-directed hands-on exposure to AWS services (EC2, IAM, S3, CloudWatch, Security Groups/SSH) via personal labs.",
        notes="Must never be merged with FactSet professional AWS claim.",
    ),
    EvidenceItem(
        claim="Git / Bitbucket — additional learning",
        category="Tool",
        employer="Self-Directed / Personal",
        role="Self-directed learning",
        employment_period="N/A",
        professional_status="Self-Directed",
        usage_level="Exposure",
        context="Additional learning/project exposure; no confirmed professional job-context use.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Self-directed exposure to Git/Bitbucket.",
    ),
    EvidenceItem(
        claim="Bachelor of Commerce (Accounting Hons)",
        category="Education",
        employer="Education",
        role="Student",
        employment_period="2018–2021",
        professional_status="Professional-Confirmed",
        usage_level="Unknown",
        context="North Orissa University.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Bachelor of Commerce (Accounting Hons), North Orissa University, 2018–2021.",
    ),
    EvidenceItem(
        claim="Excel / Advanced Excel",
        category="Tool",
        employer="Multiple / Cross-Employer",
        role="Across roles",
        employment_period="2021–2026",
        professional_status="Professional-Confirmed",
        usage_level="Frequent",
        context="Confirmed across career evidence; used in support and operations contexts.",
        evidence_source="Career Profile; master_profile.md",
        confirmation_status="Confirmed-by-User",
        safe_wording="Used Excel / Advanced Excel for analysis, reporting, and operational support tasks.",
    ),
]
