"""Configuration names used by the optional OmniRoute gateway."""

OMNIROUTE_BASE_URL_ENV = "OMNIROUTE_BASE_URL"
OMNIROUTE_API_KEY_ENV = "OMNIROUTE_API_KEY"
OMNIROUTE_MODEL_ENV = "OMNIROUTE_MODEL"
DEFAULT_OMNIROUTE_BASE_URL = "http://127.0.0.1:20128/v1"
DEFAULT_OMNIROUTE_MODEL = "auto"
